### ISSUE TITLE
Deprecated features used warning

### ISSUE THREAD

**Issue by joerocklin** [johnbellone/libartifact-cookbook#1]
As of Chef 12.5.1, there are now warnings presented at the end of chef runs:

```
Deprecated features used!
  owner nil currently does not overwrite the value of owner. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :owner, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/libartifact/libraries/libartifact_file.rb:66:in `block (3 levels) in <class:ArtifactFile>'
  group nil currently does not overwrite the value of group. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :group, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/libartifact/libraries/libartifact_file.rb:67:in `block (3 levels) in <class:ArtifactFile>'
```

**Comment by tiago-cruz-movile** [comment]
Same warning here

```
Deprecated features used!
  owner nil currently does not overwrite the value of owner. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :owner, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/libartifact/libraries/libartifact_file.rb:66:in `block (3 levels) in <class:ArtifactFile>'
  group nil currently does not overwrite the value of group. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :group, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/libartifact/libraries/libartifact_file.rb:67:in `block (3 levels) in <class:ArtifactFile>'
```

**Comment by tiago-cruz-movile** [comment]
* Import libarchive version 1.0.0
*  Import libartifact version 1.3.5

```
Deprecated features used!
  owner nil currently does not overwrite the value of owner. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :owner, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/libartifact/libraries/libartifact_file.rb:66:in `block (3 levels) in <class:ArtifactFile>'
  group nil currently does not overwrite the value of group. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :group, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/libartifact/libraries/libartifact_file.rb:67:in `block (3 levels) in <class:ArtifactFile>'
```
